markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "Rakefile"]
title : Concept Extraction API

baseurl: /concept-extraction-docs
date: 2015
author: Ontotext
ASSET_PATH : assets/boddhi

collections:
  v1_3_1-docs:
    output: true
